### ISSUE TITLE
[Bug] Shield Recipe not working

### ISSUE THREAD

**Issue by supermassimo** [Darkhax-Minecraft/AdditionalBanners#4]
Crafting the shield recipe using the door doesnt work, and while looking in your code i realized the id you used for the door "oak_door". However the id for the oak door is "wooden_door", even though the ids for the other doors are using the wood type. Moreover i would like to suggest the addition of all door types to the recipe. that way, you do not need specifically oak to make it.

Thank you very much and i hope to see more banners coming.

By the way, i would also like to offer my time to help you enhance this mod, by making each texture myself, as im experienced with the art of texture making, and graphic designing. I have already taken the time to make some more developed textures unlike the standard simple items. If you are interested in contacting me please do so through this github message.

Keep up with the good work, and im looking foward to hearing from you

**Comment by Darkhax** [comment]
Thank you for the report. Unfortunately I am not able to reproduce the error. My code doesn't actually maake reference to the ID. `OAK_DOOR` is the name given to the wooden door my MCP. As for adding support for the other wooden doors, that would be a great change, however it's not very practical to implement. The banner registry in MC does not support multiple meta values, wild card meta values or ore dictionary values. You can also only have one recipe per pattern, so I would have to add additional patterns for every recipe. I am forced into Mojang's system for this, which isn't very flexible. I may look in to adding multiple door patterns, however it would probably make more sense to create unique patterns based on the door style rather than making 6 shield patterns. 

I am not very good at art, which is why most of the designs are fairly basic. If you have any suggestions, or would like to offer new textures and designs, that would be very appreciated.

**Comment by supermassimo** [comment]
Thank you, this bug may also be caused by the fact that im using many other mods, maybe you could try installing them, and trying again. Said mods are attached below.

Regarding the textures, i would prefer a form of private messaging, preferably email. if you do agree, we will continue from there.

[mods1.zip](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/516651/mods1.zip)
[mods2.zip](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/516652/mods2.zip)
[mods3.zip](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/516653/mods3.zip)

**Comment by Darkhax** [comment]
The twitter handle you had mentioned is the correct one. My DMs are open to everyone. You can also email me using darkhax@epoxide.xyz.
